### ISSUE TITLE
sbt dist generates bat file that throws an error

### ISSUE THREAD

**Issue by Zohar2506** [playframework/play-java-starter-example#70]
After running sbt dist with the play-java-starter-example the following error is thrown while running the .bat file:

```
The input line is too long.
The syntax of the command is incorrect.
```

**Comment by marcospereira** [comment]
Hi @Zohar2506,

The possible solutions are listed here:

https://sbt-native-packager.readthedocs.io/en/stable/recipes/longclasspath.html

The problem is that there is a limit of how long commands can be in Windows:

https://support.microsoft.com/en-us/help/830473/command-prompt-cmd-exe-command-line-string-limitation

Best.

**Comment by marcospereira** [comment]
Closing this since there is a configuration in sbt-native-packager to solve the problem.
